blueprint:
  name: Circulation Pump Calendar Control
  description: >
    Controls a circulation pump switch (input_boolean) based on calendar state and time.

    - Turns ON the switch at 08:00 and 16:00 *if* either Airbnb or private rental calendars are active.
    - Turns OFF the switch at 12:00 and 21:00, or when both calendars are OFF.
  domain: automation
  input:
    switch_entity:
      name: Circulation Pump Switch
      description: The input_boolean used to control the circulation pump
      selector:
        entity:
          domain: input_boolean
    calendar_airbnb:
      name: Airbnb Rental Calendar
      selector:
        entity:
          domain: calendar
    calendar_private:
      name: Private Rental Calendar
      selector:
        entity:
          domain: calendar

trigger:
  - platform: time
    at: "08:00:00"
    id: turn_on_morning
  - platform: time
    at: "12:00:00"
    id: turn_off_noon
  - platform: time
    at: "16:00:00"
    id: turn_on_afternoon
  - platform: time
    at: "21:00:00"
    id: turn_off_evening
  - platform: state
    entity_id:
      - !input calendar_airbnb
      - !input calendar_private
    to: "off"
    id: turn_off_end_of_rental

condition: []

action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: turn_on_morning
              - condition: trigger
                id: turn_on_afternoon
          - condition: or
            conditions:
              - condition: state
                entity_id: !input calendar_airbnb
                state: "on"
              - condition: state
                entity_id: !input calendar_private
                state: "on"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input switch_entity

      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: turn_off_noon
              - condition: trigger
                id: turn_off_evening
              - condition: and
                conditions:
                  - condition: trigger
                    id: turn_off_end_of_rental
                  - condition: state
                    entity_id: !input calendar_airbnb
                    state: "off"
                  - condition: state
                    entity_id: !input calendar_private
                    state: "off"
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: !input switch_entity

mode: parallel
